server:
  port: 8080
spring:
    output:
      ansi:
        enabled: always
    profiles:
      active: dev
      include: secret
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
        - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
    datasource:
      url: jdbc:h2:./db_dev;MODE=MySQL # MODE=MySQL로 설정 (상용 db mysql 흉내내는거임)
      username: sa
      password:
      driver-class-name: org.h2.Driver
    jackson:
      serialization:
        fail-on-empty-beans: false
    jpa:
      open-in-view: false # osiv 끄는 설정(강사 스타일 타임리프, jsp할때는 안끔, 그러나 restApi 구현일때는 끔)
      hibernate:
        ddl-auto: update # 이 옵션은 항상 jpa.hibernate. 이 밑에 와야한다 이 옵션이 propertiese.hibernate로 작성해 테이블이 생성되지 않아 엄청 애먹었다...
      show-sql: true  # 콘솔에 SQL 출력
      properties:
        hibernate:
          format_sql: true   # SQL 보기 좋게 정렬
          highlight_sql: true # 색상 강조 (가능한 경우)
      logging:
        level:
          org.hibernate.SQL: debug              # 실행되는 SQL
          org.hibernate.type.descriptor.sql: INFO # 바인딩되는 파라미터 값

custom:
    site:
      name: "my site"
    accessToken:
      expirationSec: 600 # 10분

logging:
  level:
    com.ll.demo03: debug

